[package]
name = "test_bind"
version = "0.1.0"
edition = "2021"

[lib]
name = "test_bindings"
path = "src/lib/bindings.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[build-dependencies]
cc = "1.0"
bindgen = "0.59.0"

[dependencies]
